### PR TITLE
Remove emojihash from Neptune Dashboard Overview

### PR DESCRIPTION
**Pull request by zkclay**
This is my first contribution to Neptune  that addresses Issue #26 

## Before Change

Screenshot from 2024-04-08 16-02-36

## After Change Image

Screenshot from 2024-04-10 12-50-47

I didn't quite follow in the code why the default value of of the timestamp is July 1, 2024, or perhaps value this is explained by some issue syncing to the blockchain on my machine, I am open to feedback on this.

### CODE REVIEW

**Comment by dan-da** [comment]
hi @zkclay.  Welcome, and thanks for the PR!

The change looks fine/good and it seems to meet the requirements of #26 as stated.

What #26 omitted is that our dependency crate twenty-first has removed emojihash entirely in v0.39, and there are several other places in neptune-core that use it.   I count 9 files.  So those references will need to be removed as well.

If you feel comfortable doing that, it could be a good exercise for you to familiarize with the codebase a bit more.  If not, I think we could merge this PR as-is, and then I can follow up.

**Comment by Sword-Smith** [comment]
The tip digest should still be shown, just not emojified :)

**Comment by zkclay** [comment]
@dan-da @Sword-Smith Thanks for taking a look! I will work on making these changes

**Comment by zkclay** [comment]
@dan-da @Sword-Smith I have made the requested changes, could you please take a look when you have a chance?

**Comment by Sword-Smith** [comment]
Looks good. LGTM.

**Comment by Sword-Smith** [comment]
Thanks for the PR. I should probably have squashed the commits before merging though. Oh, well.

**Comment by zkclay** [comment]
@Sword-Smith Thanks, this is exciting! I'll look around for something else to pick up

**Comment by Sword-Smith** [comment]
Hope to see more PRs from you in the future :)

**Pull request merged**
